name: Build and test Windows wheels

on:
  pull_request:
  push:
    branches:
      - main
      - nightly
      - release/*
    tags:
        # NOTE: Binary build pipelines should only get triggered on release candidate builds
        # Release candidate tags look like: v1.11.0-rc1
        - v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+
  workflow_dispatch:

jobs:
  generate-matrix:
    uses: pytorch/test-infra/.github/workflows/generate_binary_build_matrix.yml@main
    with:
      package-type: wheel
      os: windows
      test-infra-repository: pytorch/test-infra
      test-infra-ref: main
      with-rocm: false
      with-cpu: false

  substitute-runner:
    needs: generate-matrix
    outputs:
      matrix: ${{ steps.substitute.outputs.matrix }}
    runs-on: ubuntu-latest
    steps:
      - name: Substitute runner
        id: substitute
        run: |
          echo matrix="$(echo '${{ needs.generate-matrix.outputs.matrix }}' | sed -e 's/windows.8xlarge.nvidia.gpu/windows.g5.4xlarge.nvidia.gpu/g')" >> ${GITHUB_OUTPUT}

  build:
    needs: substitute-runner
    permissions:
      id-token: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - repository: pytorch/tensorrt
            pre-script: packaging/pre_build_script_windows.sh
            env-script: packaging/vc_env_helper.bat
            smoke-test-script: packaging/smoke_test_windows.py
            package-name: torch_tensorrt
    name: Build torch-tensorrt whl package
    uses: pytorch/test-infra/.github/workflows/build_wheels_windows.yml@main
    with:
      repository: ${{ matrix.repository }}
      ref: ""
      test-infra-repository: pytorch/test-infra
      test-infra-ref: main
      build-matrix: ${{ needs.substitute-runner.outputs.matrix }}
      pre-script: ${{ matrix.pre-script }}
      env-script: ${{ matrix.env-script }}
      smoke-test-script: ${{ matrix.smoke-test-script }}
      package-name: ${{ matrix.package-name }}
      trigger-event: ${{ github.event_name }}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}-${{ inputs.repository }}-${{ github.event_name == 'workflow_dispatch' }}-${{ inputs.job-name }}
  cancel-in-progress: true
