# This is a basic workflow to help you get started with Actions

name: Generate Docs

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    container:
      image: docker.io/pytorch/manylinux-builder:cuda12.1
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{github.head_ref}}
      - name: Select python
        run: |
          export PATH=/opt/python/cp311-cp311/bin/:$PATH
      - name: Install base deps
        run: |
          python3 -m pip install pyyaml
          VERSION_SUFFIX=cu121 ./packaging/pre_build_script.sh
      - name: Get HEAD SHA
        id: vars
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Build Python Package
        run: |
          python3 -m pip install pip --upgrade
          CUDA_HOME=/usr/local/cuda-12.1 CI_BUILD=1 python3 -m pip install --pre -e . --extra-index-url https://download.pytorch.org/whl/nightly/cu121
      - name: Generate New Docs
        run: |
          cd docsrc
          yum install -y doxygen pandoc
          python3 -m pip install -r requirements.txt
          python3 -c "import torch_tensorrt; print(torch_tensorrt.__version__)"
          make html
          cd ..
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
        # Required
          commit_message: "docs: [Automated] Regenerating documenation for ${{ steps.vars.outputs.sha }}"
          commit_options: "--no-verify --signoff"
          file_pattern: docs/
          commit_user_name: Torch-TensorRT Github Bot
          commit_user_email: torch-tensorrt.github.bot@nvidia.com
          commit_author: Torch-TensorRT Github Bot <torch-tensorrt.github.bot@nvidia.com>
