# This is a basic workflow to help you get started with Actions

name: Generate Docs

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]

jobs:
  build-docs:
    runs-on: ubuntu-20.04
    container:
      image: docker.io/pytorch/manylinux-builder:cuda12.1
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{github.head_ref}}
      - name: Install base deps
        run: |
          ./packaging/pre_build_script.sh
      - name: Get HEAD SHA
        id: vars
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Get Bazel version
        id: bazel_info
        run: echo "version=$(cat .bazelversion)" >> $GITHUB_OUTPUT
      - name: Build Python Package
        run: |
          cp toolchains/ci_workspaces/WORKSPACE.x86_64.cu121.release.rhel WORKSPACE
          python -m pip install pip<=23
          python -m pip install --pre -e . --extra-index-url https://download.pytorch.org/whl/nightly/cu121
      - name: Generate New Docs
        run: |
          cd docsrc
          python -m pip install -r requirements.txt
          python -c "import torch_tensorrt; print(torch_tensorrt.__version__)"
          make html
          cd ..
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
        # Required
          commit_message: "docs: [Automated] Regenerating documenation for ${{ steps.vars.outputs.sha }}"
          commit_options: "--no-verify --signoff"
          file_pattern: docs/
          commit_user_name: Torch-TensorRT Github Bot
          commit_user_email: torch-tensorrt.github.bot@nvidia.com
          commit_author: Torch-TensorRT Github Bot <torch-tensorrt.github.bot@nvidia.com>
