name: Release Linux wheels and tarball

on:
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  release_tar_ball:
    permissions:
      packages: write
    env:
      PYTHON_VERSION: 3.10
      CU_VERSION: cu124
    name: release_tar_ball
    runs-on: linux.4xlarge.nvidia.gpu
    container:
      image: 'ghcr.io/pytorch/tensorrt/torch_tensorrt:2951_merge_cxx11_abi'
      options: '--gpus all'
    timeout-minutes: 120
    steps:
      - name: Clean workspace
        shell: bash -l {0}
        run: |
          set -euxo pipefail
          echo "::group::Cleanup debug output"
          rm -rf "${GITHUB_WORKSPACE}"
          mkdir -p "${GITHUB_WORKSPACE}"

          if [[ "${{ inputs.architecture }}" = "aarch64" ]]; then
            rm -rf "${RUNNER_TEMP}/*"
          fi

          echo "::endgroup::"
      - uses: actions/checkout@v3
        with:
          # Support the use case where we need to checkout someone's fork
          repository: ${{ inputs.test-infra-repository }}
          ref: ${{ inputs.test-infra-ref }}
          path: test-infra
      - name: Build CXX11-ABI Tarball
        shell: bash -l {0}
        run: |
          set -euxo pipefail
          cd /opt/torch_tensorrt
          bazel build //:libtorchtrt --compilation_mode opt --config=default
          mkdir release
          # example: 2.4.0.dev20240610+cu124, we don't want the +cu124 part, so remove +cu124
          PYTORCH_VERSION=$(python -c "import torch; print(torch.__version__)")
          PYTORCH_VERSION=${PYTORCH_VERSION%+*}
          TORCHTRT_VERSION=2.5.0
          cp bazel-bin/libtorchtrt.tar.gz \
          release/libtorchtrt-${TORCHTRT_VERSION}-tensorrt${TENSORRT_VERSION}-cuda${CU_VERSION}-libtorch${PYTORCH_VERSION}-x86_64-linux.tar.gz

      # NB: Only upload to GitHub after passing smoke tests
      - name: Upload wheel to GitHub
        continue-on-error: true
        uses: actions/upload-artifact@v3
        with:
          name: release-tarball
          path: /opt/torch_tensorrt/release

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}-${{ inputs.repository }}-${{ github.event_name == 'workflow_dispatch' }}-${{ inputs.job-name }}
  cancel-in-progress: true