name: Release Windows wheels

on:
  pull_request:

jobs:
  generate-matrix:
    uses: pytorch/test-infra/.github/workflows/generate_binary_build_matrix.yml@main
    with:
      package-type: wheel
      os: windows
      test-infra-repository: pytorch/test-infra
      test-infra-ref: main
      with-rocm: false
      with-cpu: false

  build:
    needs: generate-matrix
    permissions:
      id-token: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - repository: pytorch/tensorrt
            pre-script: packaging/pre_build_script_windows.sh
            env-var-script: packaging/env_vars.txt
            smoke-test-script: packaging/smoke_test_windows.py
            package-name: torch_tensorrt
    name: Build torch-tensorrt whl package
    # env:
    #   CU_VERSION: ${{ build-matrix.desired_cuda }}
    #   PYTHON_VERSION: ${{ build-matrix.python_version }}
    uses: pytorch/test-infra/.github/workflows/build_wheels_windows.yml@main
    # if: ${{ build-matrix.desired_cuda == 'cu121' }}
    with:
      repository: ${{ matrix.repository }}
      ref: ""
      test-infra-repository: pytorch/test-infra
      test-infra-ref: main
      build-matrix: ${{ needs.generate-matrix.outputs.matrix }}
      env-var-script: ${{ matrix.env-var-script }}
      pre-script: ${{ matrix.pre-script }}
      smoke-test-script: ${{ matrix.smoke-test-script }}
      package-name: ${{ matrix.package-name }}
      trigger-event: ${{ github.event_name }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true